name: New Padawan Request
run-name: new-padawan-request
on:
  issues:
    types:
      - opened
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygsheets numpy
      - name: execute py script # run file
        run: |
          echo github.event.issue.number = ${{ github.event.issue.number }}
          echo "Store: ${{ github.event.issue.number }}"
          INPUT_STORE=${{ github.event.issue.number }} python3 new_padawan.py
